theme: jekyll-theme-slate

title: [Daniel M Riley]
description: [I am a PhD student at Florida State University studying Formal Methods in
the Computer Science Department under the guidance of Dr. Grigory Fedyukovich.

My previous education includes B.S. degrees from FSU in Physics and Exercise Science.]
